### ISSUE TITLE
[BUG] Run serve command with -d options failed

### ISSUE THREAD

**Issue by bigBron** [spiral/roadrunner-binary#25] opened 2021-03-26 08:35 UTC
in windows system run *rr.exe serve* command with *-d* option that get error prompt:
> listen tcp :6061: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by 48d90782** [comment] 2021-03-26 13:17
Hey @bigBron, nice to meet you. Could you please share your config and version of the RR?

**Comment by bigBron** [comment] 2021-03-29 09:26
@48d90782 Sorry, no more details. I have deleted the project. It should be the latest version. It is installed with composer. The configuration file is the default configuration.
I looked at the source code, use -d option will be fixed listening port 6061, whether the program can be adjusted to be more flexible?

**Comment by 48d90782** [comment] 2021-03-29 09:29
@bigBron That depends on the version you use. But in general, `-d` flag in the RR2 is the debug/pprof flag which you should not use other than for profiling your own plugin or profiling RR2 itself.

**Comment by 48d90782** [comment] 2021-03-29 09:30
For the application, you have `http.address` or `rpc.address` for the RPC.

**Comment by bigBron** [comment] 2021-03-29 09:38
Is it possible to configure the debug/pprof port instead? In some cases 6061 will be occupied？
https://github.com/spiral/roadrunner-binary/blob/3eeefb48d27084bc63474da09735feb583344a3b/internal/cli/root.go#L71-L74

**Comment by 48d90782** [comment] 2021-03-29 09:41
Not at the moment, but just don't use `-d` flag. It is for internal usage.

**Comment by 48d90782** [comment] 2021-03-29 09:43
It's not equivalent to the RR1 `-d` flag which was used to show debug messages. Debug logging level can be configured by adding `logs` section. See: https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml

**Comment by bigBron** [comment] 2021-03-30 06:29
Oh. dude, I confused the concept, thank you for your patience reply.

**Comment by 48d90782** [comment] 2021-03-30 08:16
@bigBron np, I'll check the report you sent and if I confirm it we will definitely fix it 💯

**Comment by 48d90782** [comment] 2021-04-11 16:56
@bigBron Sorry, I can't reproduce your error. It seems, that when you used `-d` flag, some other application already listened to the `:6061` port on some interface:
![image](https://user-images.githubusercontent.com/8040338/114313554-9f025400-9aff-11eb-8c50-2ac31240cdde.png)
![image](https://user-images.githubusercontent.com/8040338/114313583-bb05f580-9aff-11eb-9709-9b3bcef8cb75.png)

I'm closing this ticket, but, feel free to reopen it if you for some unknown reason still have this issue.

**Closed by 48d90782** 2021-04-11 16:56 UTC
Labels: B-bug, F-need-verification
